### PR TITLE
src file cleanup and compile fix for FreeBSD

### PR DESCRIPTION
**Pull request by uqs**

### CODE REVIEW

**Comment by Flamefire** [comment]
Why do you remove the BOM? We recently converted all main src files to contain the BOM because otherwise IDEs like eclipse mess with UTF8 chars like German umlaute

**Comment by uqs** [comment]
BOMs are more trouble than they are worth it. Are you sure Eclipse can't properly deal with these when run in an UTF locale? At work we don't use BOMs and people work on our code base with dozens of different editors, without and problems it seems.

vim, emacs, and co work just fine without the BOM. This is what vim has to say about them:

'bomb'                  boolean (default off)            
                        local to buffer                  
                        {not in Vi}                      
                        {only available when compiled with the +multi_byte
                        feature}                         
        When writing a file and the following conditions are met, a BOM (Byte
        Order Mark) is prepended to the file:            
        - this option is on                              
        - the 'binary' option is off                     
        - 'fileencoding' is "utf-8", "ucs-2", "ucs-4" or one of the little/big
          endian variants.                               
        Some applications use the BOM to recognize the encoding of the file.
        Often used for UCS-2 files on MS-Windows.  For other applications it
        causes trouble, for example: "cat file1 file2" makes the BOM of file2
        appear halfway the resulting file.  Gcc doesn't accept a BOM.
        When Vim reads a file and 'fileencodings' starts with "ucs-bom", a
        check for the presence of the BOM is done and 'bomb' set accordingly.
        Unless 'binary' is set, it is removed from the first line, so that you
        don't see it when editing.  When you don't change the options, the BOM
        will be restored when writing the file.          

We are no longer in the 90ies and BOMs should dies.

**Comment by uqs** [comment]
Oh, and also, BOMs are useless for UTF-8, because the byte order in UTF-8 is defined. They are only needed for ucs-2 or UTF-16 to differentiate between Big Endian and Little Endian.

**Comment by Flamefire** [comment]
I had this yesterday with @MarcusSt 
Then I think we should do another commit on all submodules that (again) removes BOM. This shouldn't change the file at all (besides first 2 bytes) so history/blame is ok.
@MarcusSt mentioned that the problem was maybe, that no UTF8 encoding was used.

**Comment by uqs** [comment]
Sooo, do you want me to revert to CRLF so that my pull request can be applied?

What are most developers using anyway, Windows or Unix?

**Comment by Flamefire** [comment]
I'd say don't mess with new lines. Always keep them like they are and have git set them to the style you like.
Changing new lines means changing the whole line destroying the blame history

I use windows, some others do too. There are also a couple of linux devs, so I guess there is no real preference. May @Flow86 can say something about that?

**Comment by Flow86** [comment]
source files should be kept LF, but dont change them if they're not. We can change the line endings soon as most of the problems are fixed

**Comment by uqs** [comment]
Please have another look, this is now only the compile fix for FreeBSD

**Pull request merged**
