### PR TITLE
Build as a static library

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/Return-To-The-Roots/s25client/issues/637.

### CODE REVIEW

**Comment by Flamefire** [comment]
Don't see a reason not to do this. Anything? @Flow86

**Comment by susnux** [comment]
Yes this is probably the best solution, either build it as static library or as object.

**Comment by Mailaender** [comment]
See https://build.opensuse.org/request/show/514714 for an integration test.

**Comment by Flow86** [comment]
no, this breaks windows as mygettext is linked to multiple dlls (and so we get multiple internal states) thats why it was a dll

**Comment by Flamefire** [comment]
Oh. Can you revert this then and update the submodule in the client again?

**Comment by Mailaender** [comment]
However in a way where it won't break Linux. Before it created a dependency on `libmygettext.so` without installing it. RPM picked it up and it created an unfulfillable requirement. https://bugzilla.opensuse.org/show_bug.cgi?id=1037920

**Comment by Flamefire** [comment]
Isn't the so needed on Linux too? 
If not just make a switch for windows to build as shared there

**Comment by Mailaender** [comment]
> Isn't the so needed on Linux too?

Apparently not. With this patch the game is still localized.

**Comment by Flamefire** [comment]
Yes but the driver libraries might use a different localization which won't be obvious. Without this patch the game shouldn't run, should it? Because the so will be missing. So it sounds like the install command for it is simply missing which was never noticed.

**Comment by susnux** [comment]
The problem is: You create a shared library mygettext and link rttr against it.
But you do not install it, so the game does not run because it can not find mygettext.
rttr is also the only program which uses this, so it might be linked into rttr as a static library or simply as an object.

But I have no idea why this should not work on Windows (I do not have a Windows installation to test this), so this might be the best option if Windows really does not like to link against this build as a static library:

    if(WIN32)
        add_library(... SHARED ...)
    else()
        add_library(... STATIC ...)
    endif()

**Comment by Flow86** [comment]
the bug simply is that the mygettext.so seems not to get installed at all.

sure we could switch it to static on linux (but this cause trouble with loadable objects like in windows) or we simply fix the install?

**Comment by Flamefire** [comment]
@susnux: the problem is (at least on windows and maybe Linux) that the lib is linked into the main binary and the driver binary. using a static build means each of them would have an own state (in effect different localization) opposed to having one shared library and hence a shared state. 
So Imo it just needs to be shared and installed

**Pull request merged**
